import { StyleSheet } from "react-native";
import { Colors } from "@/theme/colors";

export const styles = StyleSheet.create({
  container: {
    position: "absolute",
    left: 40,
    top: 40,
  },

  box: {
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: Colors.black,
    backgroundColor: "transparent",
  },

  boxInactive: {
    borderWidth: 0,
  },

  content: {
    flex: 1,
    overflow: "hidden",
    borderRadius: 12,
  },

  deleteBtn: {
    position: "absolute",
    top: -20,
    right: 0,
    width: 10,
    height: 10,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20, // handleTR(10)보다 높게 설정
    // 터치 영역 확대
    padding: 10,
    margin: -10,
  },

  rotateHandle: {
    position: "absolute",
    top: -25,
    left: "50%",
    marginLeft: -12,
    width: 24,
    height: 24,
    zIndex: 100,

    padding: 10,
    margin: -10,
    alignItems: "center",
    justifyContent: "center",
  },
  rotateArrow: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  // 회전 핸들과 상단 중앙 핸들 사이 연결선
  rotateConnector: {
    position: "absolute",
    top: -15,
    left: "50%",
    width: 2,
    height: 10,
    backgroundColor: Colors.black,
    marginLeft: -1,
    zIndex: 99,
  },


  // 모서리 핸들
  handleBR: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },
  handleBL: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },
  handleTR: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },
  handleTL: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },

  // 변 중간 핸들
  handleR: {
    position: "absolute",
    right: 0,
    top: "45%",
    marginTop: -3,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },
  handleL: {
    position: "absolute",
    left: 0,
    top: "45%",
    marginTop: -3,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },
  handleT: {
    position: "absolute",
    top: 0,
    left: "50%",
    marginLeft: -7,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },
  handleB: {
    position: "absolute",
    bottom: 0,
    left: "50%",
    marginLeft: -7,
    width: 6,
    height: 6,
    borderRadius: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.black,
    zIndex: 10,
    padding: 6,
    margin: -6,
  },
});